### ISSUE TITLE
文章：字符编码   URL 错误 

### ISSUE THREAD

**Issue by xushibo** [Vonng/pigsty.io#1]
https://pigsty.cc/zh/blog/admin/collate/   这篇文章内的连接：字符编码 https://pigsty.cc/zh/blog/2018/07/01/%E7%90%86%E8%A7%A3%E5%AD%97%E7%AC%A6%E7%BC%96%E7%A0%81/
应该是 https://pigsty.cc/zh/blog/db/character-encoding/

**Comment by Vonng** [comment]
感谢反馈，已经修复
